name: ui_practice
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # 상태 관리
  provider: ^6.0.5
  get: ^4.7.2

  # 네트워크 / 데이터 통신
  http: ^1.1.0
  dio: ^5.8.0+1
  http_parser: ^4.1.2
  mime: ^2.0.0

  # 로컬 저장소
  shared_preferences: ^2.5.2
  path_provider: ^2.1.2

  # UI/UX & 위젯
  flutter_spinkit: ^5.2.1
  cached_network_image: ^3.3.1
  photo_view: ^0.15.0
  auto_size_text: ^3.0.0
  visibility_detector: ^0.4.0+2
  font_awesome_flutter: ^10.8.0
  animations: ^2.0.7
  smooth_page_indicator: ^1.2.1

  # 멀티미디어
  video_player: ^2.8.1
  image_picker: ^1.1.2
  image_cropper: ^9.1.0

  # Firebase
  firebase_core: ^2.24.2
  firebase_analytics: ^10.8.0
  firebase_crashlytics: ^3.4.5
  firebase_messaging: ^14.7.10

  # 인증 & 계정 연동
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^6.1.4
  games_services: ^4.1.0

  # 블록체인/지갑 연동
  web3dart: ^2.7.3
  bip39: ^1.0.6
  bip32: ^2.0.0
  convert: ^3.1.1

  # 플랫폼/네이티브 연동
  permission_handler: ^12.0.0+1
  connectivity_plus: ^6.1.3
  device_info_plus: ^11.3.0
  package_info_plus: ^8.3.0
  advertising_id: ^2.0.0
  flutter_keyboard_visibility: ^6.0.0
  restart_app: ^1.3.2

  # 유틸리티
  intl: ^0.20.2
  decimal: ^2.3.2
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  characters: ^1.3.0

  # 기타
  flutter_local_notifications: ^19.1.0
  webview_flutter: ^4.11.0
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
